export class AppConfig {
  static readonly API_BASE: string = 'https://echoing.negentropypixels.me';
  static readonly SHARED_FOREST_API_BASE: string = 'https://echoing.negentropypixels.me';
  static readonly CHAT_HISTORY_CLOUD_BASE: string = 'https://echoing.negentropypixels.me';
  static readonly AI_CHAT_COMPLETIONS_PROXY_URL: string = 'https://echoing.negentropypixels.me/v1/chat/completions';
  static readonly AI_MODEL: string = 'deepseek-ai/DeepSeek-V4-Flash';
}
